name: myfbd
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.32.0
  firebase_auth: ^4.19.2
  firebase_ui_auth: ^1.14.0
  firebase_ui_localizations: ^1.14.0
  firebase_ui_oauth_google: ^1.2.13
  cloud_firestore: ^4.17.1
  http: ^1.2.1
  shared_preferences: ^2.2.2
 # Google sign-in
  google_sign_in: ^6.2.1


  # Google REST APIs & auth helpers
  googleapis: ^13.1.0          # Docs / Drive live here
  googleapis_auth: ^1.4.1      # authenticatedClient helper
  url_launcher: ^6.2.5
  flutter_riverpod: ^2.4.0 

     


  cloud_functions: ^4.5.5

  # --- Utilities ---
  intl: any
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  intl_utils: ^2.8.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/gsheets_credentials.json

  # Localization configuration
 

flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: firebase_ui_el.arb
  output-localization-file: firebase_ui_localizations.dart
