// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7B0t2pwE0KYuGpF91wIoLEEVLhvOuuTI',
    appId: '1:697374211054:web:a48d3c1c6b527c4f0d2cff',
    messagingSenderId: '697374211054',
    projectId: 'principals-app',
    authDomain: 'principals-app.firebaseapp.com',
    storageBucket: 'principals-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS_5d3Z8wTPKYVsbeH_DioDKNVuc-zEyk',
    appId: '1:697374211054:android:ec6fe5030d4d218b0d2cff',
    messagingSenderId: '697374211054',
    projectId: 'principals-app',
    storageBucket: 'principals-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7B0t2pwE0KYuGpF91wIoLEEVLhvOuuTI',
    appId: '1:697374211054:web:3c16678ae99155980d2cff',
    messagingSenderId: '697374211054',
    projectId: 'principals-app',
    authDomain: 'principals-app.firebaseapp.com',
    storageBucket: 'principals-app.firebasestorage.app',
  );
}
